const data = {
  experiences: [
    {
      name: "Whale Watch Tarifa",
      description:
        "Excursiones en barco en el Estrecho de Gibraltar para ver siete especies de cetáceos. Salidas especiales para ver Orcas en julio y agosto. Expertos en cetáceos informan a los pasajeros. Pioneros en la Peninsula Iberica, desde 1996.",
      currentBookings: [],
      maxCount: 10,
      featuredImage:
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1689163947/gomyecotrip/pexels-rudolf-kirchner-831084_k8uafh.jpg",
      galleryImgs: [
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1689163947/gomyecotrip/pexels-nahuel-robledo-16035420_c6e0sa.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1689163946/gomyecotrip/pexels-timon-cornelissen-12801528_cxh3em.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1689163947/gomyecotrip/pexels-nahuel-robledo-16035416_c135li.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1689163947/gomyecotrip/pexels-wayne-6262405_webi7q.jpg",
      ],
      type: ["Art and culture", "Leisure", "Food and drink", "Sports"],
      hosted: "",
      address: "Rambla del Poblenou, 156, 08018 Barcelona",
      hasGroup: true,
      minPersonForGroup: 12,
      phoneNumber: "934 817 272",
      ratesForPerson: {
        adults: 15.5,
        kids: 9.0,
        babies: 3.0,
      },
      map: {
        lat: 41.40706251243749,
        lng: 2.1946674306853113,
      },
      saleOff: false,
      isAds: false,
      amenities: [
        "amenitie 1",
        "amenitie 2",
        "amenitie 3",
        "amenitie 4",
        "amenitie 5",
      ],
      reviewStart: 4.75,
      reviewCount: 350,
    },
    {
      name: "Ecocorneyana",
      description:
        "En Corneyana y partiendo de un huerto o corralada y de cuatro edificaciones anexas, dos cuadras y dos casas, en desuso y semiderruidas que fueron construidas en su día siguiendo la suave pendiente de la ladera, lo que motiva los tres niveles actuales en la planta baja, hemos conseguido hacer habitable, y muy agradable, lo que en el año 2000 parecía un montón de piedras, tejas de 200 años, ladrillos posiblemente romanos, vigas de castaño y roble condenado a ser reducido a un solar.",
      currentBookings: [],
      maxCount: 10,
      featuredImage:
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641209394/gomyecotrip/image-1641209393394_pszhcj.jpg",
      galleryImgs: [
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641209404/gomyecotrip/image-1641209402628_mdnzki.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641209401/gomyecotrip/image-1641209399907_sjvzvc.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641209418/gomyecotrip/image-1641209416619_m3avdx.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641209428/gomyecotrip/image-1641209427323_osm9ee.jpg",
      ],
      type: ["Art and culture", "Leisure"],
      hosted: "",
      address: "Corneyana Campomanes Lena, s/n, 33620 Asturias",
      hasGroup: true,
      minPersonForGroup: 12,
      phoneNumber: "647 380 512",
      ratesForPerson: {
        adults: 10.5,
        kids: 13.0,
        babies: 0.0,
      },
      map: {
        lat: 41.40706251243749,
        lng: 2.1946674306853113,
      },
      saleOff: false,
      isAds: false,
      amenities: [
        "amenitie 1",
        "amenitie 2",
        "amenitie 3",
        "amenitie 4",
        "amenitie 5",
      ],
      reviewStart: 4.75,
      reviewCount: 350,
    },
    {
      name: "Finca Botanico",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tempor elementum faucibus. Etiam lacus est, ullamcorper sed ipsum sit amet, dapibus tristique diam. Morbi dignissim, justo at mattis consequat, elit tortor mollis risus, vel rutrum libero mauris vel arcu. Vivamus velit orci, varius non sagittis ac, pharetra in sem. Nullam eget scelerisque magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur aliquet venenatis velit, ut gravida orci malesuada vitae. Etiam at rhoncus nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus mi neque, tempus quis luctus placerat, facilisis sit amet nulla. Curabitur vehicula nisl dui, in consequat magna laoreet vel. Integer at massa metus. Vestibulum ut justo non elit eleifend auctor. Maecenas varius tristique purus, eget pulvinar massa.",
      currentBookings: [],
      maxCount: 10,
      featuredImage:
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641159157/gomyecotrip/image-1641159156723_nv9tk1.jpg",
      galleryImgs: [
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641208963/gomyecotrip/image-1641208961930_pfgzxm.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641208968/gomyecotrip/image-1641208967757_vv3noh.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641159155/gomyecotrip/image-1641159153907_o9aygy.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641159157/gomyecotrip/image-1641159156716_itcd0n.jpg",
      ],
      type: ["Art and culture", "Leisure", "Food and drink", "Sports"],
      hosted: "",
      address: "Calle Tarajal, 30, 35544 Guatiza",
      hasGroup: true,
      minPersonForGroup: 12,
      phoneNumber: "619 591 579",
      ratesForPerson: {
        adults: 15.5,
        kids: 9.0,
        babies: 3.0,
      },
      map: {
        lat: 41.40706251243749,
        lng: 2.1946674306853113,
      },
      saleOff: false,
      isAds: false,
      amenities: [
        "amenitie 1",
        "amenitie 2",
        "amenitie 3",
        "amenitie 4",
        "amenitie 5",
      ],
      reviewStart: 4.75,
      reviewCount: 350,
    },
    {
      name: "Rappel en Sima de las Cotorras.",
      description:
        "Admira la belleza de un Cañón de más de 120 mts, haremos un descenso de 50 mts para conocer las pinturas rupestres y tendremos la oportunidad de observar una comunidad de cotorras que salen de la misma (únicamente en temporada de verano). Realizaremos un rappel en la cavidad circular de 180 metros de diámetro y 125 de profundidad, en donde también duermen cientos de cotorras que al amanecer salen en círculos ascendentes para regresar por la noche; al finalizar el ascenso se realiza un pequeño sendero perimetral en el interior de la sima observando algunas pinturas rupestres, posteriormente traslado a tu hotel.",
      currentBookings: [],
      maxCount: 10,
      featuredImage:
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641207191/gomyecotrip/image-1641207189378_b9krbg.jpg",
      galleryImgs: [
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641206867/gomyecotrip/image-1641206865203_gfqvoe.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641206853/gomyecotrip/image-1641206851888_syqh3u.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641207210/gomyecotrip/image-1641207208765_i4slbo.jpg",
        "https://res.cloudinary.com/pablopsdigital/image/upload/v1641586667/gomyecotrip/image-1641586667217_svbq7w.jpg",
      ],
      type: ["Art and culture", "Leisure", "Food and drink", "Sports"],
      hosted: "",
      address: "Calle Tarajal, 30, 35544 Guatiza",
      hasGroup: true,
      minPersonForGroup: 12,
      phoneNumber: "619 591 579",
      ratesForPerson: {
        adults: 15.5,
        kids: 9.0,
        babies: 3.0,
      },
      map: {
        lat: 41.40706251243749,
        lng: 2.1946674306853113,
      },
      saleOff: false,
      isAds: false,
      amenities: [
        "amenitie 1",
        "amenitie 2",
        "amenitie 3",
        "amenitie 4",
        "amenitie 5",
      ],
      reviewStart: 4.75,
      reviewCount: 350,
    },
  ],
};

module.exports = data;
